const js = [
  /package-lock\.json$/, // generated by npm
  /npm-shrinkwrap\.json$/, // generated by npm
  /\.min\.(js|css)$/, // generated by minify tools
  /\.(js|css)\.map$/, // generated by js bundlers/transpilers
  /node_modules\//, // generated by npm
  /yarn\.lock$/, // yarn version of package-lock
  /\.yarn\//, // yarn version of node_modules
  /(^|\/)\.pnp\..*$/, // yarn module resolution scripts
  /pnpm-lock\.yaml$/, // pnpm version of package-lock
  /(^|\/)shrinkwrap\.(yaml|json)$/ // pnpm version of shrinkwrap
];

const python = [
  /Pipfile\.lock$/,
  /__pycache__\//,
];

const java = [
  /(^|\/)\.m2\//,
];

const dotnet = [
  /\.designer\.(cs|vb)$/i, // Visual Studio designer partial classes 
  /\.feature\.cs$/i, // Visual Studio SpecFlow feature file
];

const ruby = [
  /Gemfile\.lock$/,
];

const php = [
  /composer\.lock$/,
];

const swift = [
  /(^|\/)\.swiftpm\//,
  /Package\.resolved$/,
];

const go = [
  /Gopk\.lock/,
  /glide\.lock/,
  /vendor\/((?!-)[-0-9A-Za-z]+(?<!-)\.)+(com|edu|gov|in|me|net|org|fm|io)/, // Godep vendor tree files
  /Godeps\//,
  // TODO: go.mod ?
  // TODO: go.sum ?
];

const IDEs = [
  /(^|\/)\.idea\//,
  /(^|\/)\.vscode\//,
  /(^|\/)\.vim\//,
  /(^|\/)\.xcodeproj\//,
  /\.nib$/,
  /\.xcworkspacedata$/,
  /\.xcuserstate$/,
  // TODO: .sln ?
  // TODO: .vcxproj ?
];

const matchers = [
  ...js,
  ...python,
  ...java,
  ...dotnet,
  ...ruby,
  ...php,
  ...swift,
  ...go,
  ...IDEs,
];

export const isCodeGen = (path: string): boolean => !!matchers.find(matcher => matcher.test(path));
